#Gives a list of Named Entities
#Only works correctly when undergo no preprocessing

named_entities: False


#Process Tfidf results through SVD and gives a matrix
#Requirements tf_idf 

latent_semantic_analysis: False



# Gives top 5 concepts for each document in relation to corpus
# Requirements LSA to work

LSA_Concepts: False



# Outputs corpus clusters
# Requirements LSA
# If running kmeans enter a number for the maximum amount of clusters, if not enter False
# Number of docs must be greater than number of clusters
# Ex -> kmeans: False or kmeans: 6

kmeans: False



# Process corpus for term frequency inverse document frequency

tf_idf: False


#Shows how much each topic is represented in each document
#Needs bag_of_words
#Change empty list into list with objects: config for training data location, percentage into training data, number of topics
#LDA: [path, Use_Pretrained_Model, Pct_Of_Training, Num_Of_Topics, Update_Model, Save_Model]

#	-path (string)				If want to use a pretrained model stored in a file, enter path. If want to create new model, set to False

#	-Num_Of_Topics (Integer)		Enter number of topics, If preset model is used it is already set in pretrained model

#	-Save_Model (BOOL)		         If want to save model, set to True. If not, set to False

LDA: ['C:\Users\597667\scitext-explorer\LDA_model', 3, False]





#Gives a dictionary of words with their frequency

bag_of_words: False



# Gives a table of words with their frequency
# Only works when bag_of_words is True

word_frequency_table: False



# do T or F to turn on or off
